In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [90]:
K = 100
T = 1
S = 100
r = 0.06
N = 3
u = 1.1
sigma = np.log(u)/np.sqrt(T)


In [205]:
dt = T/(N)
d = 1/u
B = np.exp(r*dt)
p = (B-d)/(u-d)
q = 1-p

stock_prices = np.zeros((N+1,N+1))
option_prices = stock_prices.copy()
stock_prices[-1] = S*d**(np.arange(N, -1, -1)) * u**(np.arange(0, N+1, 1))
option_prices[-1] = np.maximum(stock_prices[-1] - K, np.zeros(N+1))
display(option_prices, '\n', stock_prices)


array([[ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , 10. , 33.1]])

'\n'

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [ 75.13148009,  90.90909091, 110.        , 133.1       ]])

In [206]:
for i in range(N, 0, -1):
    new_row =  (p * option_prices[i, 1:i+1:] + q * option_prices[i, :i])/B
    option_prices[i-1, :i] = new_row

option_prices


array([[10.1457358 ,  0.        ,  0.        ,  0.        ],
       [ 3.25450292, 15.44712278,  0.        ,  0.        ],
       [ 0.        ,  5.70482508, 22.98013267,  0.        ],
       [ 0.        ,  0.        , 10.        , 33.1       ]])

np.float64(0.9704455335485082)

In [197]:
j = 3
display(option_prices[j, 1:j+1], option_prices[j, : j])

array([ 0. , 10. , 33.1])

array([ 0.,  0., 10.])